# Generated by Django 3.1.4 on 2021-09-12 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('collection', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=256)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('search_item', models.CharField(max_length=256)),
                ('excepted_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=256)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.JSONField()),
                ('created_date', models.DateTimeField()),
                ('entities', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(max_length=256)),
                ('lang', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
    ]
