# Generated by Django 3.1.4 on 2021-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
