# Generated by Django 3.1.4 on 2021-09-14 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='collect_size',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(18000)], verbose_name='Collect size'),
        ),
        migrations.AddField(
            model_name='tag',
            name='get_data',
            field=models.BooleanField(default=False, verbose_name='Get Data'),
        ),
        migrations.AddField(
            model_name='tag',
            name='lang',
            field=models.CharField(default='en', max_length=10, verbose_name='Language'),
        ),
    ]
