version: "3.7"
services:
  db:
    image: "postgres:12-alpine"
    networks:
      - twitter-analyser
    volumes:
      - "twitter-analyser_postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/twitter-analyser-postgres-passwd
      - POSTGRES_USER_FILE=/run/secrets/twitter-analyser-postgres-user
      - POSTGRES_DB_FILE=/run/secrets/twitter-analyser-postgres-db
    secrets:
      - twitter-analyser-postgres-db
      - twitter-analyser-postgres-user
      - twitter-analyser-postgres-passwd
    # env_file: .env # you can use this in development
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  web-server:
    image: "nginx:alpine"
    ports:
      - 80:80
      - 443:443
    networks:
      - twitter-analyser
    volumes:
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "../nginx/ssl:/etc/nginx/custome-ssl"
      - "twitter-analyser_static:/static"
      - "twitter-analyser_media:/media"
    depends_on:
      - twitter-analyser
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  twitter-analyser:
    image: "twitter-analyser:latest"
    env_file: ../../source/.env
    volumes:
      - "twitter-analyser_media:/home/app/source/media"
      - "twitter-analyser_static:/home/app/source/static"
      - "../../source/base/settings.py:/home/app/source/base/settings.py"
    secrets:
      - twitter-analyser-postgres-db
      - twitter-analyser-postgres-user
      - twitter-analyser-postgres-passwd
      - twitter-analyser-secret-key
    networks:
      - twitter-analyser
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        max_attempts: 5

networks:
  twitter-analyser:
    # driver: overlay

volumes:
  twitter-analyser_postgres:
    external: true
  twitter-analyser_media:
    external: true
  twitter-analyser_static:
    external: true

secrets:
  twitter-analyser-postgres-passwd:
    external: true
  twitter-analyser-postgres-user:
    external: true
  twitter-analyser-postgres-db:
    external: true
  twitter-analyser-secret-key:
    external: true
